/* 
    Driver for lis35de accelerometer working on SPI bus.
    Capabilities: 
        TBF
*/
#include "gpio_definition.h"
#include "spi.h"

// GPIO Connection, Specify HW pin connections inside gpio_definition.h located under platform/ directory
#define LIS35DE_CS PLATFORM_LIS35DE_CS_PIN
#define LIS35DE_CS_PINGROUP PLATFORM_LIS35DE_CS_PINGROUP

#define LIS35DE_MOSI PLATFORM_LIS35DE_MOSI_PIN
#define LIS35DE_MOSI_PINGROUP PLATFORM_LIS35DE_MOSI_PINGROUP

#define LIS35DE_MISO PLATFORM_LIS35DE_MISO_PIN
#define LIS35DE_MISO_PINGROUP PLATFORM_LIS35DE_MISO_PINGROUP

#define LIS35DE_SCK PLATFORM_LIS35DE_SCK_PIN
#define LIS35DE_SCK_PINGROUP PLATFORM_LIS35DE_SCK_PINGROUP

//Register mapping
/* 
    *_BASE is: Location inside sensor, send it inside command frame.
    *_TYPE is:
        -RO : Read Only
        -RW : Read & Write
*/
#define REGISTER_TYPE_RW 1
#define REGISTER_TYPE_RO 0

#define LIS35DE_REGISTER_CTRL_REG1_BASE 0b0100000
#define LIS35DE_REGISTER_CTRL_REG1_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_CTRL_REG2_BASE 0b0100001
#define LIS35DE_REGISTER_CTRL_REG2_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_CTRL_REG3_BASE 0b0100010
#define LIS35DE_REGISTER_CTRL_REG3_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_HP_FILTER_RESET_BASE 0b0100011
#define LIS35DE_REGISTER_HP_FILTER_RESET_TYPE REGISTER_TYPE_RO

#define LIS35DE_REGISTER_STATUS_REG_BASE 0b0100111
#define LIS35DE_REGISTER_STATUS_REG_TYPE REGISTER_TYPE_RO

#define LIS35DE_REGISTER_OUTX_BASE 0b0101001
#define LIS35DE_REGISTER_OUTX_TYPE REGISTER_TYPE_RO

#define LIS35DE_REGISTER_OUTY_BASE 0b0101011
#define LIS35DE_REGISTER_OUTY_TYPE REGISTER_TYPE_RO

#define LIS35DE_REGISTER_OUTZ_BASE 0b0101101
#define LIS35DE_REGISTER_OUTZ_TYPE REGISTER_TYPE_RO

#define LIS35DE_REGISTER_FF_WU_CFG_1_BASE 0b0110000
#define LIS35DE_REGISTER_FF_WU_CFG_1_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_FF_WU_SRC_1_BASE 0b0110001
#define LIS35DE_REGISTER_FF_WU_SRC_1_TYPE REGISTER_TYPE_RO

#define LIS35DE_REGISTER_FF_WU_THS_1_BASE 0b0110010
#define LIS35DE_REGISTER_FF_WU_THS_1_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_FF_WU_DURATION_1_BASE 0b0110011
#define LIS35DE_REGISTER_FF_WU_DURATION_1_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_FF_WU_CFG_2_BASE 0b0110100
#define LIS35DE_REGISTER_FF_WU_CFG_2_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_FF_WU_SRC_2_BASE 0b0110101
#define LIS35DE_REGISTER_FF_WU_SRC_2_TYPE REGISTER_TYPE_R0

#define LIS35DE_REGISTER_FF_WU_THS_2_BASE 0b0110110
#define LIS35DE_REGISTER_FF_WU_THS_2_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_FF_WU_DURATION_2_BASE 0b0110111
#define LIS35DE_REGISTER_FF_WU_DURATION_2_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_CLICK_CFG_BASE 0b0111000
#define LIS35DE_REGISTER_CLICK_CFG_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_CLICK_SRC_BASE 0b0111001
#define LIS35DE_REGISTER_CLICK_SRC_TYPE REGISTER_TYPE_RO

#define LIS35DE_REGISTER_CLICK_THSY_X_BASE 0b0111011
#define LIS35DE_REGISTER_CLICK_THSY_X_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_CLICK_THSZ_BASE 0b0111100
#define LIS35DE_REGISTER_CLICK_THSZ_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_CLICK_TIMELIMIT_BASE 0b0111101
#define LIS35DE_REGISTER_CLICK_TIMELIMIT_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_CLICK_LATENCY_BASE 0b0111110
#define LIS35DE_REGISTER_CLICK_LATENCY_TYPE REGISTER_TYPE_RW

#define LIS35DE_REGISTER_CLICK_WINDOW_BASE 0b0111111
#define LIS35DE_REGISTER_CLICK_WINDOW_TYPE REGISTER_TYPE_RW

// functions 
void lis35de_init(void);

void lis35de_send(uint8_t *data, int size);

void lis35de_receive (uint8_t *data, int size);

void CS_Enable (void);

void CS_Disable (void);
